name: Linux Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        configuration: [Debug, Release]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        # Install available wxWidgets packages
        sudo apt-get install -y \
          build-essential \
          cmake \
          pkg-config \
          libgtk-3-dev
        
        # Try to install wxWidgets 3.2 first, fall back to 3.0 if not available
        sudo apt-get install -y libwxgtk3.2-dev || \
        sudo apt-get install -y libwxgtk3.0-gtk3-dev
    
    - name: Set WXWIN environment variable
      run: |
        # Find wxWidgets installation path
        if [ -d "/usr/include/wx-3.2" ]; then
          echo "WXWIN=/usr" >> $GITHUB_ENV
        elif [ -d "/usr/include/wx-3.0" ]; then
          echo "WXWIN=/usr" >> $GITHUB_ENV
        else
          echo "WXWIN=/usr" >> $GITHUB_ENV
        fi
    
    - name: Build project (Linux)
      run: |
        cd build
        mkdir -p generated
        cd generated
        cmake -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
        make -j$(nproc)
    
    - name: Test executable (Linux)
      run: |
        # Check multiple possible locations for the executable
        echo "Searching for executable..."
        find build -name "wxTimelineCtrlTest*" -type f 2>/dev/null || echo "No files found with find"
        
        # List contents of build directory
        echo "Contents of build/generated:"
        ls -la build/generated/ || echo "build/generated directory not found"
        
        # Check common locations
        possible_paths=(
          "build/generated/wxTimelineCtrlTest"
          "build/generated/app/wxTimelineCtrlTest"
          "build/generated/${{ matrix.configuration }}/wxTimelineCtrlTest"
          "build/generated/Debug/wxTimelineCtrlTest"
          "build/generated/Release/wxTimelineCtrlTest"
        )
        
        executable_found=false
        for path in "${possible_paths[@]}"; do
          if [ -f "$path" ]; then
            echo "[OK] Executable found: $path"
            ls -lh "$path"
            executable_found=true
            break
          fi
        done
        
        if [ "$executable_found" = false ]; then
          echo "[ERROR] Executable not found in any expected location"
          echo "Full directory structure:"
          find build -type f -name "*" 2>/dev/null || echo "Find command failed"
          exit 1
        fi
    
    - name: Upload Linux artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: wxTimelineCtrl-Linux-${{ matrix.configuration }}
        path: |
          build/generated/**/wxTimelineCtrlTest
        retention-days: 30
